name: 'Infer# PR'

inputs:
  sarif_path: # change this
    required: true
    description: 'Path to SARIF file'
  github_token:
    required: true
    description: 'GitHub token for PR comments'
outputs:
  updated_sarif_path:
    description: 'Path to updated SARIF file'
runs:
  using: 'node16'
  main: 'dist/index.js'
