name: 'Infer# PR'
description: 'SARIF -> Fixes and PR Comments'
author: 'DeepPrompt Team'
inputs:
  sarif_path: # change this
    required: true
    description: 'Path to SARIF file'
outputs:
  updated_sarif_path:
    description: 'Path to updated SARIF file'
runs:
  using: 'node16'
  main: 'dist/index.js'
